<!-- REFERENCES -->
<div class="entry-content faq-references faq-section">
	<header>
		<h2 id="ref">References</h2>
	</header>
	<ol style="list-style: decimal;">
		<li>(BDE1) Buffed.de - ESO Preview and Interview with Creative Director Paul Sage <a href="http://www.buffed.de/TES-The-Elder-Scrolls-Online-PC-239823/Videos/The-Elder-Scrolls-Online-Preview-und-Interview-mit-Creative-Director-Paul-Sage-Englische-Version-1061243/" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(DE1) Destructoid - ESO Will Fully Support First Person Play <a href="http://www.destructoid.com/elder-scrolls-online-will-fully-support-first-person-play-248674.phtml" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(ESO1) The Elder Scrolls Online Official Website <a href="http://elderscrollsonline.com" target="_blank" rel="nofollow">[LINK]</a></li>
		<li>(ESO2) An Introduction to The Elder Scrolls Online <a href="http://youtube.com/embed/KxJTsq2XeKY" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(ESO3) Alliances at War <a href="http://youtube.com/embed/EDHa-77cy3I" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(ESO4) Conflict in Cyrodiil <a href="http://elderscrollsonline.com/en/news/post/2013/03/28/conflict-in-cyrodiil-part-1" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(ESO5) ESO on Next-Gen Consoles and New Gameplay Trailer <a href="http://elderscrollsonline.com/en/news/post/2013/06/10/eso-on-next-gen-consoles-and-new-gameplay-trailer" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(ESO6) ESO Support Page <a href="http://help.elderscrollsonline.com/" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(ESO7) Ask Us Anything: Aldmeri Dominion <a href="http://elderscrollsonline.com/en/news/post/2012/12/10/ask-us-anything-aldmeri-dominion-part-1" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(ESO7) Journey to Coldharbour <a href="http://elderscrollsonline.com/en/news/post/2013/05/02/journey-to-coldharbour" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(FB1) Elder Scrolls Online Facebook - Introduction to the Lore of Elder Scrolls Online <a href="https://www.facebook.com/notes/the-elder-scrolls-online/introduction-to-the-lore-of-the-elder-scrolls-online-en/486381251371913" target="_blank" rel="nofollow">[LINK]</a></li>
		<li>(G4E3) G4 Elder Scrolls Online E3 Gameplay Demo <a href="http://www.youtube.com/embed/iiHMdCF9kNc" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(GI1) Game Informer - June 2012 Cover Article <a href="http://www.gameinformer.com/p/elderscrollsonline.aspx" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(GI2) Game Informer - The Origins of The Elder Scrolls Online <a href="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=610&amp;height=343&amp;flashID=myExperience1630402384001&amp;bgcolor=%23FFFFFF&amp;playerID=1437116750001&amp;wmode=opaque&amp;playerKey=AQ~~%2CAAAAoc2oABE~%2CIUzEHGPD39saIEVvaP5ftuWBPP3iKw7w&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=false&amp;%40videoPlayer=1630402384001&amp;autoStart=&amp;debuggerID=&amp;startTime=1344908595099" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(GI3) Game Informer - The Challenge of The Elder Scrolls: An Interview With The Creative Director <a href="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=610&amp;height=343&amp;flashID=myExperience1626382832001&amp;bgcolor=%23FFFFFF&amp;playerID=1437116750001&amp;wmode=opaque&amp;playerKey=AQ~~%2CAAAAoc2oABE~%2CIUzEHGPD39saIEVvaP5ftuWBPP3iKw7w&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=false&amp;%40videoPlayer=1626382832001&amp;autoStart=&amp;debuggerID=&amp;startTime=1344908652246" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(GI4) Game Informer - Faction Profile: Daggerfall Covenant <a href="http://www.gameinformer.com/games/the_elder_scrolls_online/b/pc/archive/2012/05/14/elder-scrolls-online-faction-profile-daggerfall-covenant.aspx" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(GI5) Game Informer - Faction Profile: Aldmeri Dominion <a href="http://www.gameinformer.com/games/the_elder_scrolls_online/b/pc/archive/2012/05/16/elder-scrolls-online-faction-profile-aldmeri-dominion.aspx" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(GI6) Game Informer - Faction Profile: Ebonheart Pact <a href="http://www.gameinformer.com/games/the_elder_scrolls_online/b/pc/archive/2012/05/18/elder-scrolls-online-faction-profile-ebonheart-pact.aspx" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(GI7) Game Informer - Creating the Story for the Elder Scrolls Online <a href="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=610&amp;height=343&amp;flashID=myExperience1640676579001&amp;bgcolor=%23FFFFFF&amp;playerID=1437116750001&amp;wmode=opaque&amp;playerKey=AQ~~%2CAAAAoc2oABE~%2CIUzEHGPD39saIEVvaP5ftuWBPP3iKw7w&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=false&amp;%40videoPlayer=1640676579001&amp;autoStart=&amp;debuggerID=&amp;startTime=1344908688712" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(GI8) Game Informer - Exploring Quests In The Elder Scrolls Online <a href="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=610&amp;height=343&amp;flashID=myExperience1640615311001&amp;bgcolor=%23FFFFFF&amp;playerID=1437116750001&amp;wmode=opaque&amp;playerKey=AQ~~%2CAAAAoc2oABE~%2CIUzEHGPD39saIEVvaP5ftuWBPP3iKw7w&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=false&amp;%40videoPlayer=1640615311001&amp;autoStart=&amp;debuggerID=&amp;startTime=1344908724124" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(GI9) Game Informer - The Tactical Combat Of The Elder Scrolls Online <a href="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=610&amp;height=343&amp;flashID=myExperience1640551649001&amp;bgcolor=%23FFFFFF&amp;playerID=1437116750001&amp;wmode=opaque&amp;playerKey=AQ~~%2CAAAAoc2oABE~%2CIUzEHGPD39saIEVvaP5ftuWBPP3iKw7w&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=false&amp;%40videoPlayer=1640551649001&amp;autoStart=&amp;debuggerID=&amp;startTime=1345052111313" target="_blank" rel="nofollow">[VIDEO 1]</a><a href="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=610&amp;height=343&amp;flashID=myExperience1640810408001&amp;bgcolor=%23FFFFFF&amp;playerID=1437116750001&amp;wmode=opaque&amp;playerKey=AQ~~%2CAAAAoc2oABE~%2CIUzEHGPD39saIEVvaP5ftuWBPP3iKw7w&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=false&amp;%40videoPlayer=1640810408001&amp;autoStart=&amp;debuggerID=&amp;startTime=1345052112154" target="_blank" rel="nofollow">[VIDEO 2]</a></li>
		<li>(GI10) Game Informer - Special Edition Podcast: The Elder Scrolls Online <a href="http://www.gameinformer.com/b/podcasts/archive/2012/05/31/special-edition-podcast-the-elder-scrolls-online.aspx" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(GF1) GameFront - ESO Preview <a href="http://www.gamefront.com/the-elder-scrolls-online-preview-its-like-skyrim-online/" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(GN1) Games.on.net - We Go Hands-On with ESO <a href="http://games.on.net/2013/03/australian-exclusive-we-go-hands-on-with-the-elder-scrolls-online/" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(GSE3) Gamespot E3 2012 Live Show - Day 2 <a href="http://www.youtube.com/embed/JnLbl4bYxVs" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(IDT1) International Digital Times - Paul Sage Interview <a href="http://www.idigitaltimes.com/articles/15056/20130204/elder-scrolls-online-beta-skill-trees-combat.htm" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(IDT2) International Digital Times - Matt Firor Interview <a href="http://www.idigitaltimes.com/articles/14930/20130130/elder-scrolls-online-beta-test-pvp-pickpocketing.htm" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(IGN1) IGN - The Elder Scrolls Online Just Might Be Awesome <a href="http://www.ign.com/articles/2013/03/19/the-elder-scrolls-online-just-might-be-awesome" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(MA1) Massively - Hands On With ESO <a href="http://massively.joystiq.com/2013/03/19/hands-on-with-the-elder-scrolls-online/" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(ME3) Machinima E3 Live Show - Day 3 <a href="http://www.youtube.com/embed/rkPgOI_kYpk" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(MH1) MMO Hut - Elder Scrolls Online Reveal Interview <a href="http://www.youtube.com/embed/ydkXzJKXwjY" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(MR1) MMORPG - Crafting in Tamriel Revealed <a href="http://www.mmorpg.com/gamelist.cfm/game/821/feature/7226/Elder-Scrolls-Online-Crafting-in-Tamriel-Revealed.html" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(MR2) MMORPG - Forum Q&amp;A with Paul Sage <a href="http://www.mmorpg.com/discussion2.cfm/thread/390321" target="_blank" rel="nofollow">[THREAD]</a></li>
		<li>(PA1) Penny Arcade - ESO Hands On <a href="http://penny-arcade.com/report/article/elder-scrolls-online-nails-the-online-stumbles-on-the-elder-scrolls-during-" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(PCG1) PC Gamer - Exclusive Developer Interview <a href="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=610&amp;height=343&amp;flashID=myExperience001&amp;bgcolor=%23FFFFFF&amp;playerID=1138066672001&amp;playerKey=AQ~~%2CAAAA3LlbpKE~%2CBMs9KnC5BE2soOi-DZzgGC7-09qgjNAG&amp;isVid=true&amp;wmode=opaque&amp;isUI=true&amp;dynamicStreaming=true&amp;%40videoPlayer=1663587562001&amp;autoStart=&amp;debuggerID=&amp;startTime=1344995285261" target="_blank" rel="nofollow">[VIDEO]</a></li>
		<li>(PCG2) PC Gamer - ESO Hands-On <a href="http://www.pcgamer.com/previews/the-elder-scrolls-online-hands-on-first-person-mode-skills-stealth-and-more/" target="_blank" rel="nofollow">[ARTICLE]</a></li>
		<li>(PGH1) PC Games Hardware - Dan Dunham Interview <a href="http://www.pcgameshardware.com/aid,1034123/The-Elder-Scrolls-Online-Improved-effects-with-DirectX-11-Exclusive-Tech-Interview/News/" target="_blank" rel="nofollow">[ARTICLE]</a></li>	
		<li>(TWIT) Elder Scrolls Online Official Twitter <a href="https://twitter.com/TESOnline" target="_blank" rel="nofollow">[LINK]</a></li>
		<li>(TF1) Tamriel Foundry - Hands-On With The Elder Scrolls Online <a href="http://tamrielfoundry.com/2012/10/eso-media-event/" target="_blank">[ARTICLE]</a></li>
		<li>(TF2) Tamriel Foundry - The Targetting Systems of ESO <a href="http://tamrielfoundry.com/2012/12/targeting-in-eso/" target="_blank">[ARTICLE]</a></li>
		<li>(TF3) Tamriel Foundry Interview: Dan Dunham <a href="http://tamrielfoundry.com/2013/03/interview-dan-dunham/" target="_blank">[ARTICLE]</a></li>
		<li>(TG1) The Guardian - Matt Firor Interview (Parts 1 and 2) <a href="http://www.guardian.co.uk/technology/gamesblog/2013/jan/28/elder-scrolls-online-interview-matt-firor" target="_blank" rel="nofollow">[ARTICLE]</a></li>	
	</ol>
</div>